### ISSUE TITLE
[MIGRATION] Incorrect namespace mapping in guide.

### ISSUE THREAD

**Issue by BioTurboNick** [maddymontaquila/maui-migration-samples#7]
The migration guide currently says to replace `Xamarin.Essentials` with `Microsoft.Maui.Essentials`, but the latter namespace doesn't exist, and it seems the members of the namespace are all being found in other namespaces?

The guide also says that `Shapes` is now in `Microsoft.Maui.Graphics`, but that doesn't seem to be the case. Instead, it appears to be in `Microsoft.Maui.Controls`

**Comment by davidortinau** [comment]
Fixed. fyi @maddymontaquila
